### ISSUE TITLE
编译错误Android

### ISSUE THREAD

**Issue by RoarRain** [onemolegames/react-native-toast-native#6]
`node_modules/react-native-toast-native/android/src/main/java/com/toast/RCTToastPackage.java:13: 错误: RCTToastPackage不是抽象的, 并且未覆盖ReactPackage中的抽象方法createJSModules()
public class RCTToastPackage implements ReactPackage {
       ^
1 个错误
:react-native-toast-native:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-toast-native:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED`

 "react": "16.0.0-alpha.12",
 "react-native": "0.46.0",

**Comment by yasemincidem** [comment]
@RoarRain yes you are right.
My package has this problem for smaller than 0.47.0 versions of "react native"  .
Because i have to change this at android because of occuring error in "0.47.0" version and greater than 0.47.0 versions.
So you should update your version of "react native" to either "0.47.0" version or bigger than "0.47.0" versions.If you don't want to upgrade "react native" version ,you must use 1.1.3 version for "react native toast native" package

**Comment by RoarRain** [comment]
Thank you for your answer，I will upgrade the react native version.

**Comment by yasemincidem** [comment]
Np.can you inform with me about this issue when you upgrade `react native` version ? So that i will close this issue.
